### ISSUE TITLE
The reports section should not display the pre and post separate analysis  

### ISSUE THREAD

**Issue by umairnazar** [umairnazar/odctmis#17]
This issue has already been communicated and fixed at wizard level when training get completed. But at individual dashboard of Advisor and PO the report section need same corrections 

![image](https://user-images.githubusercontent.com/62398810/77112393-bc730480-6a4a-11ea-9647-e260c7dde72a.png)

**Comment by Nasirkhan-259** [comment]
Resolved

**Comment by umairnazar** [comment]
Not yet resolved.
