### ISSUE TITLE
The training assessment creation screen in the wizard opens a useless view upon random clicking 

### ISSUE THREAD

**Issue by umairnazar** [umairnazar/odctmis#25]
The more description is present in the screen shot below:

![image](https://user-images.githubusercontent.com/62398810/77120524-e03e4680-6a5a-11ea-8051-a595fb7e4269.png)

**Comment by hayyan-git** [comment]
will be developed in Phase-II/ Schedule

**Comment by Nasirkhan-259** [comment]
@aqibbangash @umairnazar , The dropdown will show previous training and if somebody clicks on that previous training, that training question will be shown (We have added it in the next phase)

**Comment by Nasirkhan-259** [comment]
And this view is not opening on random clicking this is the filter if you click on the filter area it will show the filter

**Comment by aqibbangash** [comment]
I'm talking about the Search bar that is before the Dropdown. Dropdown work. Searchbar isn't working. Searchbar should filter questions based on keywords.

**Comment by aqibbangash** [comment]
This view doesn't appear normally. When we randomly clicked on the screen it somehow came up. If it is a meaningful view then either it should be always displayed or you can have a proper button to show this view.

**Comment by Nasirkhan-259** [comment]
Okay, Thanks @aqibbangash , as for now this is not functional we will hide it and in phase 2 we will show it with full functionality?

**Comment by Nasirkhan-259** [comment]
Sir need your comment on this @aqibbangash @umairnazar
