### ISSUE TITLE
In wizard while adding a trainee the gender selection is not recognizable by the user. Moreover replace "Code" with "Password"

### ISSUE THREAD

**Issue by umairnazar** [umairnazar/odctmis#27]
Currently the gender selection is grayed. It should be bright so that can easily be recognized by PO.
 
![image](https://user-images.githubusercontent.com/62398810/77121379-e2a1a000-6a5c-11ea-92d6-fa100b217183.png)

**Comment by hayyan-git** [comment]
Completed/Done

**Comment by umairnazar** [comment]
Not resolved yet.

**Comment by umairnazar** [comment]
The gender part is visible now. But following is missing

1. Code label should be renamed to Password
2. Gender "Rather not say" -> "Other"

**Comment by umairnazar** [comment]
Still says in Gender **"Rather Not Say"**
