### ISSUE TITLE
In wizard while adding trainee from the registered trainee the search bar is required

### ISSUE THREAD

**Issue by umairnazar** [umairnazar/odctmis#28]
The PO can easily find the trainee in registered trainee using search bar by Name, CNIC or email

![image](https://user-images.githubusercontent.com/62398810/77121812-e4b82e80-6a5d-11ea-9eb2-88353b8f82fa.png)

**Comment by hayyan-git** [comment]
completed/done

**Comment by umairnazar** [comment]
No search bar found.

**Comment by umairnazar** [comment]
Make name search case insensitive. E.g: Currently you cannot search 'Ahsan' with 'ahsan'

**Comment by umairnazar** [comment]
Search bar in the entire system is not properly working. At some places it searches in lower case only. In some cases its case sensitive. Video Link: https://we.tl/t-g5G1eINBFp
