### ISSUE TITLE
The Trainer and Trainee Dashboard is not designed as per the shared use case. 

### ISSUE THREAD

**Issue by umairnazar** [umairnazar/odctmis#29]
The developers need to visit the shared mock up again because the trainer dashboard is not acceptable. The dashboard should follow all the steps and data representation should be the same as present in the shared mock up.

**Comment by hayyan-git** [comment]
Completed/Done

**Comment by umairnazar** [comment]
I have compared the required and developed use case and they are not the same. Please take a look again. 

Link:  https://xd.adobe.com/view/c14c0bfb-c5fd-4cb9-723d-a7f75218fe9f-b77d/screen/1144d170-2fc7-4573-b6db-86fd36b501e3/Trainer-Dash-2-1
