### ISSUE TITLE
The option to print the training agenda in PDF and word files

### ISSUE THREAD

**Issue by umairnazar** [umairnazar/odctmis#30]
Currently the PO can not print the agenda he developed on the wizard. The dialog box to print the agenda is required.

![image](https://user-images.githubusercontent.com/62398810/77124268-35cb2100-6a64-11ea-8896-3e015031c381.png)

**Comment by hayyan-git** [comment]
Completed/Done

**Comment by umairnazar** [comment]
@hayyan-git . I have tested again but unable to verify. Please  ensure this in wizard for all users. 

![image](https://user-images.githubusercontent.com/62398810/78890836-c7d0b300-7a7f-11ea-9367-8b2ca355314f.png)
